# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e0c7c36aa3530200f50baf1e080b5200dfc5335bb049298b9d0adb320136970406fd37d1da2e63ec6de4faeb68454708d38323da94503014bbfc3360b5ab2b

test:
  secret_key_base: 9dfb87372248930e31ff5b21d98123a41131043ab82708170cd6fc46a3b6803248fa6e277abb6cb9ff04108695f96784a5d2d2bd8bf575a0357c8ac176001b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
